name: Build distributions

on:
    workflow_dispatch:

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build binary wheel and source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution
      uses: actions/upload-artifact@v2
      with:
        name: binary wheel and source tarball
        path: |
          dist/*.whl
          dist/*.tar.gz
        if-no-files-found: error
